Gradient Boosting Method using decision Trees - 

In [1]:
import numpy as np 
import pandas as pd 
# import seaborn as sb 
# import matplotlib.pyplot as plt 

# from sklearn import tree 
# from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.model_selection import train_test_split, GridSearchCV 
from sklearn.metrics import accuracy_score, confusion_matrix 

import nbformat 
from IPython import get_ipython 

In [2]:
# %run "../Data_Preprocessing/data_preprocess_dtcls.ipynb" 

with open("../Data_Preprocessing/data_preprocess_dtcls.ipynb", "r", encoding="utf-8") as f:
    ntb = nbformat.read(f, as_version = 4) 

ipython = get_ipython() 

for cell in ntb.cells:
    if cell.cell_type == "code":
        print(cell.source) 

        if ("mov_cls_cleaned" in cell.source or "mov_cls" in cell.source):
            ipython.run_cell(cell.source, silent=True) 
            # ipython.run_cell_async(cell.source, silent=True) 

try:
    print("Movies Clean Data : ")
    print(mov_cls_cleaned.head())   # type: ignore 

except NameError as e:
    print(f"Variable not found: {e}")

import pandas as pd 
# import numpy as np 
# import seaborn as sb 
mov_cls = pd.read_csv('../Datasets/Movie_classification.csv', header=0)       # column tags are at zeroth index 
mov_cls 
mov_cls.shape 
mov_cls.describe() 
mov_cls.info() 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing_expense    506 non-null    float64
 1   Production_expense   506 non-null    float64
 2   Multiplex_coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  

In [3]:
mov_cls_cleaned     # type: ignore 

Marketing_expense  Production_expense  Multiplex_coverage     Budget  \
0              20.1264               59.62               0.462  36524.125   
1              20.5462               69.14               0.531  35668.655   
2              20.5458               69.14               0.531  39912.675   
3              20.6474               59.36               0.542  38873.890   
4              21.3810               59.36               0.542  39701.585   
..                 ...                 ...                 ...        ...   
501            21.2526               78.86               0.427  36624.115   
502            20.9054               78.86               0.427  33996.600   
503            21.2152               78.86               0.427  38751.680   
504            22.1918               78.86               0.427  37740.670   
505            20.9482               78.86               0.427  33496.650   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0           138.7               7.825                8.095            7.910   
1           152.4               7.505                7.650            7.440   
2           134.6               7.485                7.570            7.495   
3           119.3               6.895                7.035            6.920   
4           127.7               6.920                7.070            6.815   
..            ...                 ...                  ...              ...   
501         142.6               8.680                8.775            8.620   
502         150.2               8.780                8.945            8.770   
503         164.5               8.830                8.970            8.855   
504         162.8               8.730                8.845            8.800   
505         154.3               8.640                8.880            8.680   

     Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0              7.995           7.94  ...      109.60          223.840   
1              7.470           7.44  ...      146.64          243.456   
2              7.515           7.44  ...      147.88         2022.400   
3              7.020           8.26  ...      185.36          225.344   
4              7.070           8.26  ...      176.48          225.792   
..               ...            ...  ...         ...              ...   
501            8.970           6.80  ...      186.96          243.584   
502            8.930           7.80  ...      132.24          263.296   
503            9.010           7.80  ...      109.56          243.824   
504            8.845           6.80  ...      158.80          303.520   
505            8.790           6.80  ...      205.60          203.040   

     Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0                23            494       48000                 1   
1                42            462       43200                 0   
2                38            458       69400                 1   
3                45            472       66800                 1   
4                55            395       72400                 1   
..              ...            ...         ...               ...   
501              27            561       44800                 0   
502              20            600       41200                 0   
503              31            576       47800                 0   
504              47            607       44000                 0   
505              45            604       38000                 0   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                   1             0            0               1  
1                   0             0            1               0  
2                   0             1            0               0  
3                   1             0            1               0  
4                   0             0            1               0  
..                ...           ...

In [4]:
mov_cls_cleaned.corr()      # type: ignore 

Marketing_expense  Production_expense  \
Marketing_expense             1.000000            0.406583   
Production_expense            0.406583            1.000000   
Multiplex_coverage           -0.420972           -0.763651   
Budget                       -0.219247           -0.391676   
Movie_length                  0.352734            0.644779   
Lead_ Actor_Rating            0.380050            0.706481   
Lead_Actress_rating           0.379813            0.707956   
Director_rating               0.380069            0.707566   
Producer_rating               0.376462            0.705819   
Critic_rating                -0.184985           -0.251565   
Trailer_views                -0.443457           -0.591657   
Time_taken                    0.025694            0.015773   
Twitter_hastags               0.013518           -0.000839   
Avg_age_actors                0.059204            0.055810   
Num_multiplex                 0.383298            0.707559   
Collection                   -0.389582           -0.484754   
Start_Tech_Oscar             -0.013417           -0.024404   
3D_available_YES             -0.086805           -0.115401   
Genre_Comedy                  0.066796            0.086958   
Genre_Drama                  -0.016894           -0.026590   
Genre_Thriller               -0.037123           -0.098976   

                     Multiplex_coverage    Budget  Movie_length  \
Marketing_expense             -0.420972 -0.219247      0.352734   
Production_expense            -0.763651 -0.391676      0.644779   
Multiplex_coverage             1.000000  0.302188     -0.731470   
Budget                         0.302188  1.000000     -0.240265   
Movie_length                  -0.731470 -0.240265      1.000000   
Lead_ Actor_Rating            -0.768589 -0.208464      0.746904   
Lead_Actress_rating           -0.769724 -0.203981      0.746493   
Director_rating               -0.769157 -0.201907      0.747021   
Producer_rating               -0.764873 -0.205397      0.746707   
Critic_rating                  0.145555  0.232361     -0.217830   
Trailer_views                  0.581386  0.602536     -0.589318   
Time_taken                     0.035515  0.040439     -0.019820   
Twitter_hastags                0.004882  0.030674      0.009380   
Avg_age_actors                -0.092104 -0.064694      0.075198   
Num_multiplex                 -0.915495 -0.282796      0.673896   
Collection                     0.429300  0.696304     -0.377999   
Start_Tech_Oscar              -0.004017 -0.027148      0.016291   
3D_available_YES               0.073903  0.163774      0.005101   
Genre_Comedy                  -0.068554 -0.052579      0.092693   
Genre_Drama                    0.046393 -0.004195      0.003452   
Genre_Thriller                 0.037772  0.046251     -0.088609   

                     Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
Marketing_expense              0.380050             0.379813         0.380069   
Production_expense             0.706481             0.707956         0.707566   
Multiplex_coverage            -0.768589            -0.769724        -0.769157   
Budget                        -0.208464            -0.203981        -0.201907   
Movie_length                   0.746904             0.746493         0.747021   
Lead_ Actor_Rating             1.000000             0.997905         0.997735   
Lead_Actress_rating            0.997905             1.000000         0.998097   
Director_rating                0.997735             0.998097         1.000000   
Producer_rating                0.994073             0.994003         0.994126   
Critic_rating                 -0.169978            -0.165992        -0.166638   
Trailer_views                 -0.490267            -0.487536        -0.486452   
Time_taken                     0.038050             0.037975         0.035881   
Twitter_hastags                0.014463             0.010239         0.010077   
Avg_age_actors                 0.036794        

Variable split (X, y) : 

In [5]:
X = mov_cls_cleaned.loc[:, mov_cls_cleaned.columns != 'Start_Tech_Oscar']      # type: ignore 
X 

Marketing_expense  Production_expense  Multiplex_coverage     Budget  \
0              20.1264               59.62               0.462  36524.125   
1              20.5462               69.14               0.531  35668.655   
2              20.5458               69.14               0.531  39912.675   
3              20.6474               59.36               0.542  38873.890   
4              21.3810               59.36               0.542  39701.585   
..                 ...                 ...                 ...        ...   
501            21.2526               78.86               0.427  36624.115   
502            20.9054               78.86               0.427  33996.600   
503            21.2152               78.86               0.427  38751.680   
504            22.1918               78.86               0.427  37740.670   
505            20.9482               78.86               0.427  33496.650   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0           138.7               7.825                8.095            7.910   
1           152.4               7.505                7.650            7.440   
2           134.6               7.485                7.570            7.495   
3           119.3               6.895                7.035            6.920   
4           127.7               6.920                7.070            6.815   
..            ...                 ...                  ...              ...   
501         142.6               8.680                8.775            8.620   
502         150.2               8.780                8.945            8.770   
503         164.5               8.830                8.970            8.855   
504         162.8               8.730                8.845            8.800   
505         154.3               8.640                8.880            8.680   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
0              7.995           7.94         527367      109.60   
1              7.470           7.44         494055      146.64   
2              7.515           7.44         547051      147.88   
3              7.020           8.26         516279      185.36   
4              7.070           8.26         531448      176.48   
..               ...            ...            ...         ...   
501            8.970           6.80         492480      186.96   
502            8.930           7.80         482875      132.24   
503            9.010           7.80         532239      109.56   
504            8.845           6.80         496077      158.80   
505            8.790           6.80         518438      205.60   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
0            223.840              23            494       48000   
1            243.456              42            462       43200   
2           2022.400              38            458       69400   
3            225.344              45            472       66800   
4            225.792              55            395       72400   
..               ...             ...            ...         ...   
501          243.584              27            561       44800   
502          263.296              20            600       41200   
503          243.824              31            576       47800   
504          303.520              47            607       44000   
505          203.040              45            604       38000   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                   1             0            0               1  
1                   0             0            1               0  
2                   0             1            0               0  
3                   1             0            1               0  
4                   0             0            1               0  
..                ...           ...          ...             ...  
501                 0             0            0               0

In [6]:
X.shape 

(506, 20)

In [7]:
y = mov_cls_cleaned['Start_Tech_Oscar']      # type: ignore 
y 

0      1
1      0
2      1
3      1
4      1
      ..
501    0
502    0
503    0
504    0
505    0
Name: Start_Tech_Oscar, Length: 506, dtype: int64

In [8]:
y.shape 

(506,)

Test - Train Split : 

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 

print(f" X_train size : {X_train.shape} \n X_test size : {X_test.shape} \n y_train size : {y_train.shape} \n y_test size : {y_test.shape}") 

print(f"X_train :\n{X_train}") 
print(f"X_test :\n{X_test}") 
print(f"y_train :\n{y_train}") 
print(f"y_test :\n{y_test}") 

 X_train size : (404, 20) 
 X_test size : (102, 20) 
 y_train size : (404,) 
 y_test size : (102,)
X_train :
     Marketing_expense  Production_expense  Multiplex_coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   
..                 ...                 ...                 ...        ...   
323            25.6784               69.76               0.507  31707.940   
192            21.7328               61.88               0.563  39873.790   
117            23.0196               75.02               0.453  33446.655   
47             24.5854               68.82               0.552  33496.650   
172            22.7828               63.10  

In [10]:
X_train = pd.DataFrame(X_train, columns=list(X.columns))  
X_train 

Marketing_expense  Production_expense  Multiplex_coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   
..                 ...                 ...                 ...        ...   
323            25.6784               69.76               0.507  31707.940   
192            21.7328               61.88               0.563  39873.790   
117            23.0196               75.02               0.453  33446.655   
47             24.5854               68.82               0.552  33496.650   
172            22.7828               63.10               0.490  30952.460   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
220         162.0               8.485                8.640            8.485   
71           91.0               7.280                7.400            7.290   
240         127.8               6.755                6.935            6.800   
6           140.1               7.065                7.265            7.150   
417         162.6               9.135                9.305            9.095   
..            ...                 ...                  ...              ...   
323         147.8               7.545                7.700            7.550   
192          99.8               6.620                6.830            6.700   
117         156.1               8.615                8.755            8.540   
47          159.0               7.085                7.180            7.125   
172         162.0               8.650                8.730            8.635   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
220            8.670           8.52         480270      174.68   
71             7.455           8.16         491978      200.68   
240            6.840           8.68         470107      204.80   
6              7.400           8.96         459241      139.16   
417            9.165           6.96         302776      172.16   
..               ...            ...            ...         ...   
323            7.765           8.08         446743      131.40   
192            6.895           7.96         515199      210.56   
117            8.595           7.44         454755      189.68   
47             7.230           7.42         374797      106.64   
172            8.790           7.68         415584      187.24   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
220          224.272              23            536       53400   
71           263.472              46            400       43400   
240          224.320              24            387       54000   
6            243.664              41            522       45800   
417          301.664              60            589       20800   
..               ...             ...            ...         ...   
323          302.960              25            501       37000   
192          225.824              40            448       72800   
117          303.072              28            609       38400   
47           242.656              44            526       33200   
172          243.696              38            530       46200   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
220                 0             0            0               1  
71                  0             0            0               0  
240                 1             1            0               0  
6                   1             0            0               1  
417                 1             0            0               0  
..                ...           ...          ...             ...  
323                 1             1            0               0

In [11]:
y_train = pd.Series(y_train) 
y_train 

220    1
71     1
240    1
6      0
417    1
      ..
323    1
192    0
117    0
47     1
172    0
Name: Start_Tech_Oscar, Length: 404, dtype: int64

Training multiple classification trees using Gradient Descent - 

In [12]:
# clstree = DecisionTreeClassifier() 
   
# grdb_cls = GradientBoostingClassifier(n_estimators=1000, criterion='friedman_mse')      
grdb_cls = GradientBoostingClassifier(n_estimators=100)      
grdb_cls.fit(X_train, y_train) 

y_train_prd = grdb_cls.predict(X_train) 
y_test_prd = grdb_cls.predict(X_test) 

In [13]:
y_train_prd 

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,

In [14]:
y_test_prd 

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0])

Model  Performance - 

In [15]:
conf_mtx_trn = confusion_matrix(y_train, y_train_prd) 
print(f"Train Confusion Matrix : \n{conf_mtx_trn}") 

conf_mtx_tst = confusion_matrix(y_test, y_test_prd) 
print(f"Test Confusion Matrix : \n{conf_mtx_tst}") 

Train Confusion Matrix : 
[[185   1]
 [  2 216]]
Test Confusion Matrix : 
[[25 19]
 [24 34]]


In [16]:
acc_sc_trn = accuracy_score(y_train, y_train_prd) 
print(f"Train Accuracy Score : {acc_sc_trn}") 

acc_sc_tst = accuracy_score(y_test, y_test_prd) 
print(f"Test Accuracy Score : {acc_sc_tst}") 

Train Accuracy Score : 0.9925742574257426
Test Accuracy Score : 0.5784313725490197


More hyperparameters usage - 

In [17]:
grdb_cls2 = GradientBoostingClassifier(learning_rate=0.02, n_estimators=1000, max_depth=1)  
grdb_cls2.fit(X_train, y_train) 

GradientBoostingClassifier(learning_rate=0.02, max_depth=1, n_estimators=1000)

In [18]:
conf_mtx_trn = confusion_matrix(y_train, grdb_cls2.predict(X_train)) 
print(f"Train Confusion Matrix : \n{conf_mtx_trn}") 

conf_mtx_tst = confusion_matrix(y_test, grdb_cls2.predict(X_test)) 
print(f"Test Confusion Matrix : \n{conf_mtx_tst}") 

Train Confusion Matrix : 
[[143  43]
 [ 53 165]]
Test Confusion Matrix : 
[[27 17]
 [22 36]]


In [19]:
acc_sc_trn = accuracy_score(y_train, grdb_cls2.predict(X_train)) 
print(f"Train Accuracy Score : {acc_sc_trn}") 

acc_sc_tst = accuracy_score(y_test, grdb_cls2.predict(X_test)) 
print(f"Test Accuracy Score : {acc_sc_tst}") 

Train Accuracy Score : 0.7623762376237624
Test Accuracy Score : 0.6176470588235294


In [20]:
grdb_cls3 = GradientBoostingClassifier(random_state=50)   
# grdb_cls3 = GradientBoostingClassifier()  

params_grid = { "learning_rate": [0.02, 0.039, 0.05, 0.086], 
                "n_estimators": [100, 500, 1000], 
                "max_depth": [1,2] 
              } 

grid_search = GridSearchCV(grdb_cls3, param_grid=params_grid, scoring='accuracy', n_jobs=-1)  
grid_search.fit(X_train, y_train)  

GridSearchCV(estimator=GradientBoostingClassifier(random_state=50), n_jobs=-1,
             param_grid={'learning_rate': [0.02, 0.039, 0.05, 0.086],
                         'max_depth': [1, 2],
                         'n_estimators': [100, 500, 1000]},
             scoring='accuracy')

In [21]:
grid_search.best_params_ 

{'learning_rate': 0.05, 'max_depth': 1, 'n_estimators': 500}

In [22]:
cv_rf_cls = grid_search.best_estimator_ 
cv_rf_cls 

GradientBoostingClassifier(learning_rate=0.05, max_depth=1, n_estimators=500,
                           random_state=50)

In [23]:
conf_mtx_trn = confusion_matrix(y_train, cv_rf_cls.predict(X_train)) 
print(f"Train Confusion Matrix : \n{conf_mtx_trn}") 

conf_mtx_tst = confusion_matrix(y_test, cv_rf_cls.predict(X_test)) 
print(f"Test Confusion Matrix : \n{conf_mtx_tst}") 

Train Confusion Matrix : 
[[144  42]
 [ 49 169]]
Test Confusion Matrix : 
[[27 17]
 [22 36]]


In [24]:
acc_sc_trn = accuracy_score(y_train, cv_rf_cls.predict(X_train)) 
print(f"Train Accuracy Score : {acc_sc_trn}") 

acc_sc_tst = accuracy_score(y_test, cv_rf_cls.predict(X_test)) 
print(f"Test Accuracy Score : {acc_sc_tst}") 

Train Accuracy Score : 0.7747524752475248
Test Accuracy Score : 0.6176470588235294
